services:
  mysql:
    image: yichuan0712/g2s-pdb2026-db:latest
    container_name: pdb-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pdb_2026
      MYSQL_USER: cbio
      MYSQL_PASSWORD: cbio
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  mysql-old:
    image: mariadb:10.0
    container_name: pdb-mariadb-old
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pdb
      MYSQL_USER: cbio
      MYSQL_PASSWORD: cbio
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data_old:/var/lib/mysql

  mongo:
    image: mongo:4.4
    container_name: pdb-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
